// ************ AUTH ************
export const AUTHENTICATE = "AUTHENTICATE"
export const LOGOUT = "LOGOUT"
export const SET_REGISTRATION_ERROR = "SET_REGISTRATION_ERROR"
// ************ Main Dashboard ************
export const SET_DISPLAY_WISHLISTS = "SET_DISPLAY_WISHLISTS"
export const ADD_WISHLIST = "ADD_WISHLIST"
export const SET_DISPLAY_ADD_WISHLIST_FORM = "SET_DISPLAY_ADD_WISHLIST_FORM"
export const SET_DISPLAY_EDIT_WISHLIST_FORM = "SET_DISPLAY_EDIT_WISHLIST_FORM"
export const DISPLAY_PARTICULAR_WISHLIST = "DISPLAY_PARTICULAR_WISHLIST"
export const DISPLAY_DELETE_POPUP = "DISPLAY_DELETE_POPUP"
// ************ WishList Dashboard ************
export const CHANGE_FORM = "CHANGE_FORM"
export const ADD_WISH_ITEM = "ADD_WISH_ITEM"
export const GET_ALL_WISHES_BY_WISHLIST_ID = "GET_ALL_WISHES_BY_WISHLIST_ID"
export const SET_DISPLAY_ADD_WISH_ITEM_FORM = "SET_DISPLAY_ADD_WISH_ITEM_FORM"
export const GO_TO_WISHLIST_DASHBOARD = "GO_TO_WISHLIST_DASHBOARD"
export const SET_WISHLIST_DATA = "SET_WISHLIST_DATA"
